# Generated by Django 3.2.3 on 2023-06-29 14:42
import json

from django.db import migrations


def load_ingredients(apps, schema_editor):
    Ingredients = apps.get_model('api', 'Ingredient')
    with open('data/ingredients.json', encoding='utf-8') as jsonfile:
        data = json.load(jsonfile)
        ingredient_list = []
        for item in data:
            Ingredients.objects.all().delete()
            ingredient_list.append(Ingredients(
                name=item['name'],
                measurement_unit=item['measurement_unit']))
        Ingredients.objects.bulk_create(ingredient_list)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(load_ingredients)
    ]
