# Generated by Django 5.1 on 2024-08-12 09:34

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3, 'Тег должен быть больше 3 символов.')], verbose_name='Тег')),
                ('slug', models.SlugField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'slug должен быть больше 3 символов.')], verbose_name='Слаг')),
                ('color', colorfield.fields.ColorField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#FFFF00', 'Yellow'), ('#FF00FF', 'Magenta'), ('#00FFFF', 'Cyan'), ('#800080', 'Purple'), ('#FFA500', 'Orange'), ('#008000', 'Dark Green'), ('#800000', 'Maroon'), ('#808080', 'Gray')], default='#FF0000', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
    ]
